### ISSUE TITLE
start: make the code to set MSP via VTOR optional

### ISSUE THREAD

**Issue by ilg-ul** [micro-os-plus/micro-os-plus-iii-cortexm#2]
On some platforms, using VTOR to get the stack address is not reliable, for example on Nordic, the soft radio firmware takes over VTOR and delegates it after processing.

**Comment by ilg-ul** [comment]
fixed on 2018-03-23

**Comment by henris42** [comment]
Hi, did you integrate this to release yet? I did test it already in 2018 when you commited the patch, works ok.

**Comment by ilg-ul** [comment]
Yes, it was merged, it should be available in `master`. I forgot to close it.
